// AUTO-GENERATED by `pnpm sync 001` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 198, narrationSplits: [77] },
  declaration     : { durationInFrames: 209, narrationSplits: [91] },
  initialization  : { durationInFrames: 208, narrationSplits: [109] },
  print           : { durationInFrames: 340, narrationSplits: [98, 144] },
} as const;
