// AUTO-GENERATED by `pnpm sync 002` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 198, narrationSplits: [107] },
  intScene        : { durationInFrames: 190, narrationSplits: [85] },
  doubleScene     : { durationInFrames: 195, narrationSplits: [92] },
  stringScene     : { durationInFrames: 179, narrationSplits: [75] },
  booleanScene    : { durationInFrames: 193, narrationSplits: [101] },
  summaryScene    : { durationInFrames: 187, narrationSplits: [85] },
} as const;
