// AUTO-GENERATED by `pnpm sync 001` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 198, narrationSplits: [77], sentenceEndFrames: [58], speechStartFrame: 4, speechEndFrame: 169, wordStartFrames: [[22,35,43],[80,91,98,113,127,139,157,159]] },
  declaration     : { durationInFrames: 209, narrationSplits: [91], sentenceEndFrames: [71], speechStartFrame: 5, speechEndFrame: 179, wordStartFrames: [[16,37,47,59],[94,99,112,125,140,151,163]] },
  initialization  : { durationInFrames: 208, narrationSplits: [109], sentenceEndFrames: [89], speechStartFrame: 5, speechEndFrame: 178, wordStartFrames: [[17,31,44,53,58,66,81],[114,119,138,155]] },
  print           : { durationInFrames: 340, narrationSplits: [98, 144], sentenceEndFrames: [74, 134], speechStartFrame: 6, speechEndFrame: 309, wordStartFrames: [[14,31,40,52,62],[101,106,112,121,139],[149,155,163,178,188,197,236,249,266,277,284,296,298]] },
} as const;
