// AUTO-GENERATED by `pnpm sync 001` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 211, narrationSplits: [77], sentenceEndFrames: [59], speechStartFrame: 5, speechEndFrame: 182, wordStartFrames: [[0,12,29,38],[77,88,97,109,129,136,155,159,163]] },
  declaration     : { durationInFrames: 224, narrationSplits: [98], sentenceEndFrames: [76], speechStartFrame: 5, speechEndFrame: 192, wordStartFrames: [[0,7,28,39,55],[91,97,97,112,122,143,154,167]] },
  initialization  : { durationInFrames: 223, narrationSplits: [118], sentenceEndFrames: [96], speechStartFrame: 5, speechEndFrame: 191, wordStartFrames: [[0,10,23,38,49,55,61,79],[109,119,134,158]] },
  interpret       : { durationInFrames: 332, narrationSplits: [87, 235], sentenceEndFrames: [65, 212], speechStartFrame: 5, speechEndFrame: 300, wordStartFrames: [[0,11,22,31,40],[78,94,104,110,118,132,149,163,173,188],[229,233,244,257,276]] },
  interpretQuiz   : { durationInFrames: 188, narrationSplits: [], sentenceEndFrames: [], speechStartFrame: 6, speechEndFrame: 155, wordStartFrames: [[0,14,21,36,53,66,93,105,124,136]] },
  interpretReveal : { durationInFrames: 152, narrationSplits: [60], sentenceEndFrames: [40], speechStartFrame: 5, speechEndFrame: 123, wordStartFrames: [[0,13],[53,62,78,91,104]] },
  print           : { durationInFrames: 365, narrationSplits: [105, 251], sentenceEndFrames: [80, 228], speechStartFrame: 6, speechEndFrame: 333, wordStartFrames: [[0,5,23,33,43],[58,107,112,122,134,158,164,182,192,206],[245,257,277,290,297,311,313]] },
} as const;
