// AUTO-GENERATED by `pnpm sync 002` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 312, narrationSplits: [104, 218], sentenceEndFrames: [84, 197], speechStartFrame: 4, speechEndFrame: 281, wordStartFrames: [[0,12,23,32,50,62],[89,110,126,134,145,157,163,164,173],[212,221,230,242,251]] },
  valueVsVar      : { durationInFrames: 315, narrationSplits: [114, 208], sentenceEndFrames: [93, 189], speechStartFrame: 6, speechEndFrame: 284, wordStartFrames: [[0,6,20,29,44,54,62],[107,116,126,137,154,167],[201,211,223,230,241,248,253,259]] },
  intScene        : { durationInFrames: 286, narrationSplits: [83, 182], sentenceEndFrames: [64, 161], speechStartFrame: 5, speechEndFrame: 255, wordStartFrames: [[0,9,23,37],[73,86,99,113,118,134,141,143],[175,184,201,217,222,233]] },
  doubleScene     : { durationInFrames: 273, narrationSplits: [80, 170], sentenceEndFrames: [62, 146], speechStartFrame: 4, speechEndFrame: 241, wordStartFrames: [[0,8,22,35],[74,83,95,112,116,125],[160,168,181,198,207,216,219]] },
  stringScene     : { durationInFrames: 369, narrationSplits: [89, 171, 265], sentenceEndFrames: [69, 152, 246], speechStartFrame: 5, speechEndFrame: 338, wordStartFrames: [[0,11,31,42],[79,94,107,120,132],[164,178,196,214],[259,269,287,305,312,315]] },
  booleanScene    : { durationInFrames: 299, narrationSplits: [97, 208], sentenceEndFrames: [79, 189], speechStartFrame: 5, speechEndFrame: 268, wordStartFrames: [[0,11,19,28,43,54],[92,100,116,125,143,143,161,169,172],[202,210,220,232,240,244]] },
  summaryScene    : { durationInFrames: 192, narrationSplits: [90], sentenceEndFrames: [69], speechStartFrame: 6, speechEndFrame: 160, wordStartFrames: [[0,9,23,23,33,46],[83,92,96,115,127,134]] },
} as const;
