// AUTO-GENERATED by `pnpm sync 002` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 313, narrationSplits: [104, 219], sentenceEndFrames: [84, 197], speechStartFrame: 4, speechEndFrame: 282, wordStartFrames: [[0,12,23,32,50,62],[98,110,126,134,145,157,163,164,173],[212,223,231,243,251]] },
  valueVsVar      : { durationInFrames: 315, narrationSplits: [114, 208], sentenceEndFrames: [93, 189], speechStartFrame: 6, speechEndFrame: 284, wordStartFrames: [[0,6,20,29,44,54,62],[107,116,126,137,154,167],[201,211,223,230,241,248,253,259]] },
  intScene        : { durationInFrames: 285, narrationSplits: [83, 181], sentenceEndFrames: [64, 161], speechStartFrame: 5, speechEndFrame: 254, wordStartFrames: [[0,9,22,37],[73,86,99,113,118,134,141,143],[175,184,200,217,221,233]] },
  doubleScene     : { durationInFrames: 274, narrationSplits: [81, 172], sentenceEndFrames: [62, 148], speechStartFrame: 5, speechEndFrame: 243, wordStartFrames: [[0,9,22,35],[76,85,97,113,117,127],[160,169,182,199,208,217,220]] },
  stringScene     : { durationInFrames: 369, narrationSplits: [89, 171, 265], sentenceEndFrames: [69, 152, 246], speechStartFrame: 5, speechEndFrame: 338, wordStartFrames: [[0,11,31,42],[79,94,107,120,132],[164,178,196,214],[259,269,287,305,312,315]] },
  booleanScene    : { durationInFrames: 299, narrationSplits: [97, 208], sentenceEndFrames: [79, 189], speechStartFrame: 5, speechEndFrame: 268, wordStartFrames: [[0,11,19,28,43,54],[92,100,116,125,143,143,161,169,172],[202,210,220,232,240,244]] },
  summaryScene    : { durationInFrames: 192, narrationSplits: [90], sentenceEndFrames: [69], speechStartFrame: 6, speechEndFrame: 160, wordStartFrames: [[0,9,23,23,33,46],[83,92,96,115,127,134]] },
} as const;
