// AUTO-GENERATED by `pnpm sync 002` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 197, narrationSplits: [51], sentenceEndFrames: [41], speechStartFrame: 4, speechEndFrame: 167, wordStartFrames: [[22,35,46],[58,73,107,116,125,135,145]] },
  intScene        : { durationInFrames: 190, narrationSplits: [85], sentenceEndFrames: [65], speechStartFrame: 5, speechEndFrame: 158, wordStartFrames: [[21,32,47],[88,97,115,131,134,145]] },
  doubleScene     : { durationInFrames: 195, narrationSplits: [92], sentenceEndFrames: [68], speechStartFrame: 5, speechEndFrame: 163, wordStartFrames: [[20,35,40,52],[93,98,114,128,137,147,150]] },
  stringScene     : { durationInFrames: 307, narrationSplits: [75, 132], sentenceEndFrames: [54, 122], speechStartFrame: 5, speechEndFrame: 276, wordStartFrames: [[22,38],[79,91,100,106],[131,140,154,167,206,217,236,251,259,262]] },
  booleanScene    : { durationInFrames: 193, narrationSplits: [101], sentenceEndFrames: [82], speechStartFrame: 5, speechEndFrame: 161, wordStartFrames: [[22,28,40,52,65],[106,112,121,133,146]] },
  summaryScene    : { durationInFrames: 192, narrationSplits: [90], sentenceEndFrames: [69], speechStartFrame: 6, speechEndFrame: 160, wordStartFrames: [[11,18,32,40,54],[94,101,108,125,135,143]] },
} as const;
