// AUTO-GENERATED by `pnpm sync 003` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 293, narrationSplits: [107], sentenceEndFrames: [91], speechStartFrame: 5, speechEndFrame: 263, wordStartFrames: [[0,7,22,40,50,61],[107,128,128,149,174,197,211,223,241]] },
  addSubScene     : { durationInFrames: 208, narrationSplits: [88], sentenceEndFrames: [63], speechStartFrame: 5, speechEndFrame: 177, wordStartFrames: [[0,8,24,35,44],[72,88,104,115,122,132,142,148,159]] },
  mulDivScene     : { durationInFrames: 298, narrationSplits: [88, 200], sentenceEndFrames: [66, 180], speechStartFrame: 5, speechEndFrame: 266, wordStartFrames: [[0,10,26,37,46],[82,91,106,119,125,136,142,149,160],[194,208,219,241]] },
  remScene        : { durationInFrames: 342, narrationSplits: [121, 229], sentenceEndFrames: [99, 204], speechStartFrame: 6, speechEndFrame: 310, wordStartFrames: [[0,10,23,46,60,63,77],[115,124,132,142,156,166,183],[221,230,239,254,271,286]] },
  summaryScene    : { durationInFrames: 227, narrationSplits: [112], sentenceEndFrames: [90], speechStartFrame: 6, speechEndFrame: 195, wordStartFrames: [[0,11,25,41,41,53,65],[106,109,122,134,150,163,174,176]] },
} as const;
