// AUTO-GENERATED by `pnpm sync 003` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 274, narrationSplits: [99], sentenceEndFrames: [84], speechStartFrame: 5, speechEndFrame: 244, wordStartFrames: [[0,7,20,37,46,56],[99,119,119,138,161,182,196,206,223]] },
  addSubScene     : { durationInFrames: 194, narrationSplits: [82], sentenceEndFrames: [59], speechStartFrame: 5, speechEndFrame: 164, wordStartFrames: [[0,7,22,32,41],[71,81,97,106,113,122,131,138,147]] },
  mulDivScene     : { durationInFrames: 278, narrationSplits: [82, 186], sentenceEndFrames: [61, 167], speechStartFrame: 5, speechEndFrame: 248, wordStartFrames: [[0,8,24,34,42],[76,84,98,110,116,127,133,138,149],[179,193,203,223]] },
  remScene        : { durationInFrames: 308, narrationSplits: [102, 202], sentenceEndFrames: [81, 179], speechStartFrame: 5, speechEndFrame: 277, wordStartFrames: [[0,9,22,43,52,62],[93,103,111,121,134,143,158],[194,203,211,224,240,254]] },
  summaryScene    : { durationInFrames: 212, narrationSplits: [104], sentenceEndFrames: [84], speechStartFrame: 5, speechEndFrame: 182, wordStartFrames: [[0,10,22,38,38,49,61],[98,100,113,124,139,152,161,163]] },
} as const;
