// AUTO-GENERATED by `pnpm sync 003` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 313, narrationSplits: [107], sentenceEndFrames: [91], speechStartFrame: 5, speechEndFrame: 281, wordStartFrames: [[0,7,22,40,50,61],[107,130,130,152,176,200,218,232,254]] },
  addSubScene     : { durationInFrames: 221, narrationSplits: [84], sentenceEndFrames: [63], speechStartFrame: 5, speechEndFrame: 190, wordStartFrames: [[0,8,24,35,44],[73,84,101,112,121,131,150,159,172]] },
  mulDivScene     : { durationInFrames: 319, narrationSplits: [88, 221], sentenceEndFrames: [66, 200], speechStartFrame: 5, speechEndFrame: 287, wordStartFrames: [[0,10,26,37,46],[82,91,108,119,127,140,155,165,177],[215,229,239,261]] },
  remScene        : { durationInFrames: 384, narrationSplits: [136, 265], sentenceEndFrames: [116, 244], speechStartFrame: 5, speechEndFrame: 353, wordStartFrames: [[0,10,25,51,77,81,97],[136,146,157,172,197,207,226],[265,274,282,296,314,329]] },
  summaryScene    : { durationInFrames: 227, narrationSplits: [112], sentenceEndFrames: [90], speechStartFrame: 6, speechEndFrame: 195, wordStartFrames: [[0,11,25,41,41,53,65],[106,109,122,134,150,163,174,176]] },
} as const;
