// AUTO-GENERATED by `pnpm sync 004` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 239, narrationSplits: [113], sentenceEndFrames: [95], speechStartFrame: 5, speechEndFrame: 209, wordStartFrames: [[0,5,18,27,35,45,51,60,73],[104,118,130,142,169,175,185]] },
  compareScene    : { durationInFrames: 571, narrationSplits: [97, 192, 290, 391, 475], sentenceEndFrames: [78, 170, 270, 371, 455], speechStartFrame: 5, speechEndFrame: 540, wordStartFrames: [[0,5,19,28,35,43,56],[89,96,110,120,128,134,148],[185,193,207,226,243,251],[284,290,304,323,341,350],[384,389,409,421,431],[469,474,492,504,515]] },
  summaryScene    : { durationInFrames: 204, narrationSplits: [96], sentenceEndFrames: [76], speechStartFrame: 6, speechEndFrame: 175, wordStartFrames: [[0,11,24,24,38,52],[90,90,100,109,119,119,144,157]] },
} as const;
