// AUTO-GENERATED by `pnpm sync 004` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 265, narrationSplits: [118], sentenceEndFrames: [110], speechStartFrame: 2, speechEndFrame: 241, wordStartFrames: [[2,11,30,35,43,54,62,72,85],[118,135,147,173,190,203,213]], wordStartMs: [[50,377,992,1165,1444,1810,2060,2387,2819],[3935,4502,4887,5762,6348,6781,7108]] },
  compareScene    : { durationInFrames: 805, narrationSplits: [142, 317, 454, 599, 738], sentenceEndFrames: [142, 310, 454, 599, 738], speechStartFrame: 2, speechEndFrame: 781, wordStartFrames: [[2,15,57,68,77,85,93,130],[142,182,194,206,215,228,262,275],[317,328,343,355,389,402,444],[454,468,478,486,522,537,579,591],[599,617,651,665,708,719,726],[738,753,753,753,753,753,753,753]], wordStartMs: [[50,512,1887,2262,2550,2829,3098,4329],[4723,6079,6463,6858,7156,7598,8723,9165],[10579,10935,11435,11838,12954,13387,14810],[15137,15598,15935,16194,17415,17887,19300,19694],[19954,20550,21704,22156,23608,23963,24185],[24598,25098,25098,25098,25098,25098,25098,25098]] },
  summaryScene    : { durationInFrames: 216, narrationSplits: [99], sentenceEndFrames: [92], speechStartFrame: 2, speechEndFrame: 193, wordStartFrames: [[2,12,22,32,48,64],[99,113,125,145,164,174,174,174]], wordStartMs: [[50,415,723,1060,1588,2137],[3316,3768,4163,4845,5461,5807,5807,5807]] },
} as const;
