// AUTO-GENERATED by `pnpm sync 005` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 243, narrationSplits: [118], sentenceEndFrames: [101], speechStartFrame: 5, speechEndFrame: 214, wordStartFrames: [[0,7,20,20,40,60],[73,118,118,140,163,176,176,181,191]] },
  andScene        : { durationInFrames: 311, narrationSplits: [62], sentenceEndFrames: [42], speechStartFrame: 5, speechEndFrame: 280, wordStartFrames: [[0,9,55,67,67,82,99,103,111,139,139],[148,179,184,198,205,205,226,250,262]] },
  orScene         : { durationInFrames: 282, narrationSplits: [154], sentenceEndFrames: [133], speechStartFrame: 5, speechEndFrame: 252, wordStartFrames: [[0,7,7,54,64,77,77,94,101,101],[112,147,159,159,170,194,194,199,205,223,223,235]] },
  notScene        : { durationInFrames: 243, narrationSplits: [130], sentenceEndFrames: [113], speechStartFrame: 6, speechEndFrame: 212, wordStartFrames: [[0,6,6,22,37,37,51],[79,90,130,146,146,177,177,189]] },
  summaryScene    : { durationInFrames: 300, narrationSplits: [78], sentenceEndFrames: [62], speechStartFrame: 5, speechEndFrame: 268, wordStartFrames: [[0,3,10,22,38],[38,78,91,100,118,131,154,164,176,176,189,206,230,239]] },
} as const;
