// AUTO-GENERATED by `pnpm sync 005` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 243, narrationSplits: [118], sentenceEndFrames: [101], speechStartFrame: 5, speechEndFrame: 214, wordStartFrames: [[0,7,20,20,40,60],[73,118,118,140,163,176,176,181,191]] },
  andScene        : { durationInFrames: 270, narrationSplits: [63], sentenceEndFrames: [42], speechStartFrame: 5, speechEndFrame: 239, wordStartFrames: [[0,8,56,56,67,80,96,100,100,106,122],[159,159,162,175,181,199,199,212,222]] },
  orScene         : { durationInFrames: 270, narrationSplits: [147], sentenceEndFrames: [130], speechStartFrame: 5, speechEndFrame: 240, wordStartFrames: [[0,7,7,54,64,77,77,94,101,101],[111,147,157,157,167,186,186,191,196,212,212,224]] },
  notScene        : { durationInFrames: 231, narrationSplits: [121], sentenceEndFrames: [103], speechStartFrame: 5, speechEndFrame: 201, wordStartFrames: [[0,5,5,19,32,32,45],[45,80,80,121,134,160,160,178]] },
  summaryScene    : { durationInFrames: 228, narrationSplits: [78], sentenceEndFrames: [62], speechStartFrame: 5, speechEndFrame: 198, wordStartFrames: [[0,3,10,10,22],[38,78,90,90,98,121,132,143,143,163,171]] },
} as const;
