// AUTO-GENERATED by `pnpm sync 006` — do not edit manually

export const AUDIO_CONFIG = {
  overview        : { durationInFrames: 203, narrationSplits: [97], sentenceEndFrames: [77], speechStartFrame: 5, speechEndFrame: 172, wordStartFrames: [[0,14,39,58],[88,88,101,107,125,142]] },
  intro           : { durationInFrames: 217, narrationSplits: [102], sentenceEndFrames: [81], speechStartFrame: 5, speechEndFrame: 185, wordStartFrames: [[0,14,29,37,45,58],[94,107,119,124,149,161]] },
  ifScene         : { durationInFrames: 262, narrationSplits: [104], sentenceEndFrames: [92], speechStartFrame: 9, speechEndFrame: 229, wordStartFrames: [[0,15,25,40,59,71],[104,124,135,152,164,171,190,195,207]] },
  ifElseScene     : { durationInFrames: 243, narrationSplits: [107], sentenceEndFrames: [82], speechStartFrame: 5, speechEndFrame: 211, wordStartFrames: [[0,10,22,35,40,57],[89,112,127,146,165,179,189]] },
  summaryScene    : { durationInFrames: 227, narrationSplits: [120], sentenceEndFrames: [100], speechStartFrame: 5, speechEndFrame: 195, wordStartFrames: [[0,8,20,29,38,58,71,76],[112,124,128,139,151,161,173,176]] },
} as const;
