// AUTO-GENERATED by `pnpm sync 006` — do not edit manually

export const AUDIO_CONFIG = {
  intro           : { durationInFrames: 203, narrationSplits: [95], sentenceEndFrames: [75], speechStartFrame: 5, speechEndFrame: 173, wordStartFrames: [[0,13,27,41,53,84],[84,99,112,115,137,149]] },
  ifScene         : { durationInFrames: 244, narrationSplits: [108], sentenceEndFrames: [90], speechStartFrame: 8, speechEndFrame: 213, wordStartFrames: [[0,13,23,37,55,66],[93,115,125,141,152,158,176,181,192]] },
  ifElseScene     : { durationInFrames: 227, narrationSplits: [100], sentenceEndFrames: [77], speechStartFrame: 5, speechEndFrame: 196, wordStartFrames: [[0,9,21,33,37,53],[89,104,118,136,153,166,175]] },
  summaryScene    : { durationInFrames: 214, narrationSplits: [113], sentenceEndFrames: [94], speechStartFrame: 5, speechEndFrame: 183, wordStartFrames: [[0,7,20,27,44,54,67,71],[104,117,121,131,142,152,163,165]] },
} as const;
