// AUTO-GENERATED by `pnpm sync 006` — do not edit manually

export const AUDIO_CONFIG = {
  overview        : { durationInFrames: 190, narrationSplits: [90], sentenceEndFrames: [71], speechStartFrame: 5, speechEndFrame: 160, wordStartFrames: [[0,13,36,54],[81,81,94,99,116,132]] },
  intro           : { durationInFrames: 203, narrationSplits: [95], sentenceEndFrames: [75], speechStartFrame: 5, speechEndFrame: 172, wordStartFrames: [[0,13,27,34,41,53],[82,99,111,115,137,149]] },
  ifScene         : { durationInFrames: 244, narrationSplits: [108], sentenceEndFrames: [90], speechStartFrame: 8, speechEndFrame: 213, wordStartFrames: [[0,13,23,37,55,66],[93,115,125,141,152,158,176,181,192]] },
  ifElseScene     : { durationInFrames: 227, narrationSplits: [100], sentenceEndFrames: [77], speechStartFrame: 5, speechEndFrame: 196, wordStartFrames: [[0,9,20,32,37,53],[86,104,118,136,153,166,175]] },
  summaryScene    : { durationInFrames: 212, narrationSplits: [111], sentenceEndFrames: [93], speechStartFrame: 5, speechEndFrame: 181, wordStartFrames: [[0,7,19,26,37,53,66,70],[95,115,119,129,139,149,161,163]] },
} as const;
