// AUTO-GENERATED by `pnpm sync 007` — do not edit manually

export const AUDIO_CONFIG = {
  overview        : { durationInFrames: 273, narrationSplits: [133], sentenceEndFrames: [116], speechStartFrame: 5, speechEndFrame: 241, wordStartFrames: [[0,7,23,34,40,67,86,97,99],[133,135,143,152,159,177,205,218,221]] },
  intro           : { durationInFrames: 314, narrationSplits: [163], sentenceEndFrames: [152], speechStartFrame: 7, speechEndFrame: 282, wordStartFrames: [[0,10,14,36,52,75,104,110,118,132,132],[163,175,194,206,223,244,260,262]] },
  syntaxScene     : { durationInFrames: 277, narrationSplits: [149], sentenceEndFrames: [132], speechStartFrame: 5, speechEndFrame: 245, wordStartFrames: [[0,9,17,37,43,64,81,97,112],[149,161,172,184,205,213]] },
  multiCaseScene  : { durationInFrames: 297, narrationSplits: [133], sentenceEndFrames: [116], speechStartFrame: 6, speechEndFrame: 266, wordStartFrames: [[0,4,17,28,40,52,82,96,98,133],[133,143,161,176,194,222,229,244,247]] },
  summaryScene    : { durationInFrames: 468, narrationSplits: [54, 187, 322], sentenceEndFrames: [34, 165, 303], speechStartFrame: 5, speechEndFrame: 436, wordStartFrames: [[0],[46,58,72,81,97,125,142,145],[173,191,206,220,233,245,274],[316,322,334,350,359,384,401,414,416]] },
} as const;
