// AUTO-GENERATED by `pnpm sync 008` — do not edit manually

export const AUDIO_CONFIG = {
  overview        : { durationInFrames: 178, narrationSplits: [81], sentenceEndFrames: [59], speechStartFrame: 5, speechEndFrame: 146, wordStartFrames: [[0,16,28,28],[40,70,82,82,98,118]] },
  intro           : { durationInFrames: 228, narrationSplits: [121], sentenceEndFrames: [101], speechStartFrame: 9, speechEndFrame: 196, wordStartFrames: [[0,16,30,37,41,58,70,79,79],[112,127,140,143,152,173]] },
  whileScene      : { durationInFrames: 270, narrationSplits: [123], sentenceEndFrames: [109], speechStartFrame: 6, speechEndFrame: 238, wordStartFrames: [[0,6,13,23,32,49,61,77,91],[123,140,156,170,191,212,221]] },
  executionScene  : { durationInFrames: 654, narrationSplits: [127, 239, 334, 411, 520], sentenceEndFrames: [114, 222, 315, 393, 500], speechStartFrame: 4, speechEndFrame: 622, wordStartFrames: [[0,8,17,22,45,58,71,83,96],[127,145,155,160,179,194,203],[239,252,263,267,286,299],[334,344,355,359],[411,422,430,436,460,472,480],[520,531,540,545,565,577,582,598]] },
  infiniteScene   : { durationInFrames: 199, narrationSplits: [86], sentenceEndFrames: [66], speechStartFrame: 5, speechEndFrame: 167, wordStartFrames: [[0,6,17,26,50],[80,91,104,118,128,145]] },
  summaryScene    : { durationInFrames: 176, narrationSplits: [94], sentenceEndFrames: [73], speechStartFrame: 7, speechEndFrame: 147, wordStartFrames: [[0,13,28,28,44,80],[100,100,114,119]] },
} as const;
