// AUTO-GENERATED by `pnpm sync 009` — do not edit manually

export const AUDIO_CONFIG = {
  overview        : { durationInFrames: 154, narrationSplits: [76], sentenceEndFrames: [55], speechStartFrame: 5, speechEndFrame: 122, wordStartFrames: [[0,14,25,37],[37,68,80,94]] },
  intro           : { durationInFrames: 213, narrationSplits: [109], sentenceEndFrames: [94], speechStartFrame: 4, speechEndFrame: 183, wordStartFrames: [[0,10,35,56,56,73,78,80],[109,121,121,133,152,161]] },
  forScene        : { durationInFrames: 212, narrationSplits: [107], sentenceEndFrames: [87], speechStartFrame: 7, speechEndFrame: 181, wordStartFrames: [[0,15,28,46,67],[101,107,114,119,139,151]] },
  executionScene  : { durationInFrames: 530, narrationSplits: [104, 174, 245, 317, 415], sentenceEndFrames: [84, 155, 226, 297, 395], speechStartFrame: 6, speechEndFrame: 499, wordStartFrames: [[0,8,16,21,21,37,50,64],[97,106,115,115,119,135],[169,176,186,190,190,206],[238,247,257,261,278,278],[310,317,325,331,353,364,364,371],[409,416,422,427,445,445,457,461,477]] },
  summaryScene    : { durationInFrames: 214, narrationSplits: [116], sentenceEndFrames: [102], speechStartFrame: 4, speechEndFrame: 182, wordStartFrames: [[0,9,24,50,71,85,85],[116,127,143,157]] },
} as const;
