/**
 * scripts/sync.ts
 *
 * 사용법: pnpm sync <series>/<id>
 *   예)  pnpm sync 001-Java-Basic/001
 *
 * 자동 처리:
 *  1. narration 텍스트 해시로 변경된 씬만 감지
 *  2. edge-tts 로 mp3 재생성
 *  3. ffprobe 로 실측 duration → durationInFrames 계산
 *  4. ffmpeg silencedetect(-40dB) 로 발화 시작/종료 프레임 감지 → speechStartFrame / speechEndFrame
 *  5. ffmpeg silencedetect(-25dB) 로 문장 분기 프레임 감지 → narrationSplits / sentenceEndFrames
 *  6. 결과를 <id>-audio.ts 파일로 자동 저장
 */

import { buildSync } from "esbuild";
import { createHash } from "crypto";
import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from "fs";
import { spawnSync } from "child_process";
import path from "path";

const FPS = 30;
const SCENE_TAIL_FRAMES = 15;
const PUBLIC_DIR = "public";
const SRC_DIR = "src/compositions";

// ── CLI 인수 ───────────────────────────────────────────────────
const arg = process.argv[2];
if (!arg) {
  console.error("Usage: pnpm sync <series>/<id>   e.g.  pnpm sync 001-Java-Basic/001");
  process.exit(1);
}
const argParts   = arg.split("/");
const episodeId  = argParts[argParts.length - 1];
const SERIES_DIR = path.join(SRC_DIR, ...argParts.slice(0, -1));
const compositionId = episodeId;

const matchEntry = readdirSync(SERIES_DIR).find(
  (f) => f.startsWith(episodeId + "-") && f.endsWith(".tsx")
);
if (!matchEntry) {
  console.error(`❌  ${SERIES_DIR}/${episodeId}-*.tsx 파일을 찾을 수 없습니다.`);
  process.exit(1);
}
const COMPOSITION_FILE = path.join(SERIES_DIR, matchEntry);
const COMPOSITION_DIR  = SERIES_DIR;
const CACHE_DIR = ".cache";
mkdirSync(CACHE_DIR, { recursive: true });
const HASH_FILE = `${CACHE_DIR}/${arg.replace(/\//g, "-")}-audio-hashes.json`;
console.log(`📄  ${COMPOSITION_FILE}\n`);

// ── AUDIO_CONFIG 스텁 생성 ─────────────────────────────────────
const _audioConfigBootstrap = path.join(COMPOSITION_DIR, compositionId + "-audio.ts");
if (!existsSync(_audioConfigBootstrap)) {
  writeFileSync(
    _audioConfigBootstrap,
    `// AUTO-GENERATED by \`pnpm sync ${compositionId}\` — do not edit manually\n\nconst _stub = { durationInFrames: 30, narrationSplits: [] as number[] };\nexport const AUDIO_CONFIG: Record<string, { durationInFrames: number; narrationSplits: number[] }> = new Proxy({}, { get: () => _stub });\n`,
    "utf-8"
  );
  if (existsSync(HASH_FILE)) writeFileSync(HASH_FILE, "{}", "utf-8");
}

// ── VIDEO_CONFIG 로드 ──────────────────────────────────────────
type SceneEntry = { narration?: string[]; audio: string; };

function loadConfig(): {
  VOICE: string; RATE: string;
  PRONUNCIATION: Record<string, string>;
  VIDEO_CONFIG: Record<string, SceneEntry>;
} {
  const result = buildSync({
    entryPoints: [COMPOSITION_FILE], bundle: true,
    platform: "node", format: "cjs", write: false,
    packages: "external", logLevel: "silent",
  });
  const code = result.outputFiles[0].text;
  const mod = { exports: {} as Record<string, unknown> };
  const stub = new Proxy({}, {
    get(_: object, prop: string | symbol) {
      if (prop === "then") return undefined;
      return (...args: unknown[]) => { void args; return stub; };
    },
  });
  const realRequire = require;
  const mockRequire = (id: string): unknown => {
    if (id === "react" || id === "remotion" || id.startsWith("@remotion/")) return stub;
    return realRequire(id);
  };
  new Function("module", "exports", "require", code)(mod, mod.exports, mockRequire);
  return mod.exports as ReturnType<typeof loadConfig>;
}

const { VOICE, RATE, PRONUNCIATION, VIDEO_CONFIG } = loadConfig();

// ── 유틸 ──────────────────────────────────────────────────────
type Hashes = Record<string, string>;

function hash(text: string): string {
  return createHash("sha256").update(text).digest("hex").slice(0, 16);
}
function loadHashes(): Hashes {
  if (!existsSync(HASH_FILE)) return {};
  return JSON.parse(readFileSync(HASH_FILE, "utf-8")) as Hashes;
}
function applyPronunciation(text: string): string {
  let r = text;
  for (const [k, v] of Object.entries(PRONUNCIATION)) r = r.replaceAll(k, v);
  return r;
}

// ── PRONUNCIATION 단어별 확장 ──────────────────────────────────
// display 단어 1개 → TTS 단어 배열 변환
//   "System.out.println" → ["print", "line"]
//   "(자료)"             → []               (빈 치환 = 발화 없음)
//   "int,"              → ["int,"]          (trailing 구두점 재부착)
//   "메서드를"           → ["메서드를"]     (치환 없음)
function getPronunciationExpansion(word: string, pronunciation: Record<string, string>): string[] {
  if (word in pronunciation) {
    const val = pronunciation[word].trim();
    return val === "" ? [] : val.split(/\s+/);
  }
  const stripped = word.replace(/[.,;:!?]+$/, "");
  const suffix = word.slice(stripped.length);
  if (stripped !== word && stripped in pronunciation) {
    const val = pronunciation[stripped].trim();
    if (val === "") return [];
    const parts = val.split(/\s+/);
    parts[parts.length - 1] += suffix;   // 마지막 TTS 단어에 구두점 재부착
    return parts;
  }
  return [word];
}

// ── 전역 TTS 정렬 테이블 ───────────────────────────────────────
// narration 모든 문장의 display 단어 → 전역 TTS 인덱스 매핑
// 반환값:
//   globalTtsCount: 전체 TTS 단어 수 (Whisper 인덱스 계산 기준)
//   displayWords:   각 display 단어의 (sentenceIdx, displayIdx, firstTtsIdx, ttsCount)
type DisplayWordInfo = {
  sentenceIdx: number;
  displayIdx:  number;
  firstTtsIdx: number;   // 이 단어의 TTS 단어들이 시작하는 전역 인덱스
  ttsCount:    number;   // TTS 확장 단어 수 (0 = 발화 없음)
};

export function buildGlobalAlignment(
  narration: string[],
  pronunciation: Record<string, string>,
): { globalTtsCount: number; displayWords: DisplayWordInfo[] } {
  const displayWords: DisplayWordInfo[] = [];
  let globalTtsIdx = 0;
  for (let si = 0; si < narration.length; si++) {
    const words = narration[si].split(" ");
    for (let di = 0; di < words.length; di++) {
      const expanded = getPronunciationExpansion(words[di], pronunciation);
      displayWords.push({ sentenceIdx: si, displayIdx: di, firstTtsIdx: globalTtsIdx, ttsCount: expanded.length });
      globalTtsIdx += expanded.length;
    }
  }
  return { globalTtsCount: globalTtsIdx, displayWords };
}

// ── 발화 시작/종료 프레임 감지 (speechStartFrame / speechEndFrame) ─
function detectSpeechBounds(audioFile: string, totalSecs: number): { speechStartFrame: number; speechEndFrame: number } {
  const ffRes = spawnSync(
    "ffmpeg",
    ["-i", audioFile, "-af", "silencedetect=n=-40dB:d=0.03", "-f", "null", "-"],
    { encoding: "utf-8" }
  );
  const output = (ffRes.stderr ?? "") + (ffRes.stdout ?? "");
  const silences: { start: number; end: number | null }[] = [];
  let pendingStart: number | null = null;
  for (const line of output.split("\n")) {
    const startM = line.match(/silence_start:\s*([\d.]+)/);
    if (startM) pendingStart = parseFloat(startM[1]);
    const endM = line.match(/silence_end:\s*([\d.]+)/);
    if (endM) {
      silences.push({ start: pendingStart ?? 0, end: parseFloat(endM[1]) });
      pendingStart = null;
    }
  }
  if (pendingStart !== null) silences.push({ start: pendingStart, end: null });

  let speechStartFrame = 0;
  const leading = silences.find((s) => s.start < 0.5 && s.end !== null);
  if (leading) speechStartFrame = Math.round(leading.end! * FPS);

  let speechEndFrame = Math.ceil(totalSecs * FPS);
  const trailing = [...silences].reverse().find((s) => s.end === null || s.end >= totalSecs - 0.1);
  if (trailing) speechEndFrame = Math.round(trailing.start * FPS);

  return { speechStartFrame, speechEndFrame };
}

// ── 문장 분기 프레임 감지 (narrationSplits / sentenceEndFrames) ─
function detectSplits(audioFile: string, sentenceCount: number): { splits: number[]; sentenceEndFrames: number[] } {
  if (sentenceCount <= 1) return { splits: [], sentenceEndFrames: [] };

  const probeRes = spawnSync(
    "ffprobe",
    ["-v", "quiet", "-show_entries", "format=duration", "-of", "csv=p=0", audioFile],
    { encoding: "utf-8" }
  );
  const totalSecs = parseFloat(probeRes.stdout.trim());

  const ffRes = spawnSync(
    "ffmpeg",
    ["-i", audioFile, "-af", "silencedetect=n=-25dB:d=0.2", "-f", "null", "-"],
    { encoding: "utf-8" }
  );
  const output = (ffRes.stderr ?? "") + (ffRes.stdout ?? "");

  const entries: { start: number; end: number; duration: number }[] = [];
  let pendingStart: number | null = null;
  for (const line of output.split("\n")) {
    const startM = line.match(/silence_start:\s*([\d.]+)/);
    if (startM) pendingStart = parseFloat(startM[1]);
    const m = line.match(/silence_end:\s*([\d.]+)\s*\|\s*silence_duration:\s*([\d.]+)/);
    if (m && pendingStart !== null) {
      entries.push({ start: pendingStart, end: parseFloat(m[1]), duration: parseFloat(m[2]) });
      pendingStart = null;
    }
  }

  const breaks = entries
    .filter((e) => e.end > 0.4 && e.end < totalSecs - 0.3 && e.duration > 0.25)
    .sort((a, b) => b.duration - a.duration)   // 긴 silence 우선 (문장 간 gap이 문장 내 호흡보다 길다)
    .slice(0, sentenceCount - 1)
    .sort((a, b) => a.start - b.start);         // 시간 순으로 재정렬

  return {
    splits:            breaks.map((b) => Math.round(b.end   * FPS)),
    sentenceEndFrames: breaks.map((b) => Math.round(b.start * FPS)),
  };
}

// ── AUDIO_CONFIG 파일 쓰기 ────────────────────────────────────
type SceneAudioData = {
  durationInFrames: number;
  narrationSplits: number[];
  sentenceEndFrames: number[];
  speechStartFrame: number;
  speechEndFrame: number;
  wordStartFrames: number[][];  // display 단어별 시작 프레임 (문장별, 길이 = displayWords.length)
};

function writeAudioConfig(config: Record<string, SceneAudioData>): void {
  const audioConfigFile = path.join(COMPOSITION_DIR, compositionId + "-audio.ts");
  const lines = Object.entries(config)
    .map(([k, v]) => {
      const wfStr = (v.wordStartFrames ?? []).map((s) => `[${s.join(",")}]`).join(",");
      return `  ${k.padEnd(16)}: { durationInFrames: ${v.durationInFrames}, narrationSplits: [${v.narrationSplits.join(", ")}], sentenceEndFrames: [${v.sentenceEndFrames.join(", ")}], speechStartFrame: ${v.speechStartFrame}, speechEndFrame: ${v.speechEndFrame}, wordStartFrames: [${wfStr}] },`;
    })
    .join("\n");
  const content = `// AUTO-GENERATED by \`pnpm sync ${compositionId}\` — do not edit manually\n\nexport const AUDIO_CONFIG = {\n${lines}\n} as const;\n`;
  writeFileSync(audioConfigFile, content, "utf-8");
  console.log(`\n📝  ${audioConfigFile} 업데이트 완료`);
}

// ── 메인 루프 ─────────────────────────────────────────────────
const hashes = loadHashes();
let changed = false;

const audioConfigFile = path.join(COMPOSITION_DIR, compositionId + "-audio.ts");
let existingAudioConfig: Record<string, SceneAudioData> = {};
if (existsSync(audioConfigFile)) {
  try {
    const raw = readFileSync(audioConfigFile, "utf-8");
    for (const line of raw.split("\n")) {
      const m = line.match(/^\s+(\w+)\s*:\s*\{ durationInFrames: (\d+), narrationSplits: \[([^\]]*)\], sentenceEndFrames: \[([^\]]*)\], speechStartFrame: (\d+), speechEndFrame: (\d+)/);
      if (m) {
        const splits = m[3].trim() ? m[3].split(",").map(s => parseInt(s.trim())) : [];
        const ends   = m[4].trim() ? m[4].split(",").map(s => parseInt(s.trim())) : [];
        existingAudioConfig[m[1]] = { durationInFrames: parseInt(m[2]), narrationSplits: splits, sentenceEndFrames: ends, speechStartFrame: parseInt(m[5]), speechEndFrame: parseInt(m[6]), wordStartFrames: [] };
        // wordStartFrames 중첩 배열 파싱
        const wfIdx = line.indexOf("wordStartFrames: ");
        if (wfIdx !== -1) {
          const start = line.indexOf("[", wfIdx);
          if (start !== -1) {
            let depth = 0, end = -1;
            for (let i = start; i < line.length; i++) {
              if (line[i] === "[") depth++;
              else if (line[i] === "]") { depth--; if (depth === 0) { end = i; break; } }
            }
            if (end !== -1) {
              try { existingAudioConfig[m[1]].wordStartFrames = JSON.parse(line.slice(start, end + 1)) as number[][]; } catch { /* ignore */ }
            }
          }
        }
        continue;
      }
      // 구버전 호환
      const m2 = line.match(/^\s+(\w+)\s*:\s*\{ durationInFrames: (\d+), narrationSplits: \[([^\]]*)\]/);
      if (m2) {
        const splits = m2[3].trim() ? m2[3].split(",").map(s => parseInt(s.trim())) : [];
        existingAudioConfig[m2[1]] = { durationInFrames: parseInt(m2[2]), narrationSplits: splits, sentenceEndFrames: [], speechStartFrame: 0, speechEndFrame: 0, wordStartFrames: [] };
      }
    }
  } catch { /* ignore */ }
}

const audioConfig: Record<string, SceneAudioData> = {};

for (const [key, scene] of Object.entries(VIDEO_CONFIG)) {
  const narration = scene.narration;
  if (!narration) continue;

  const ttsText = applyPronunciation(narration.join(" "));
  const audio = scene.audio;
  const newHash = hash(VOICE + RATE + ttsText);

  if (hashes[key] === newHash) {
    if (existingAudioConfig[key]) {
      audioConfig[key] = existingAudioConfig[key];
      if (audioConfig[key].speechStartFrame === 0 || audioConfig[key].speechEndFrame === 0) {
        const probeR = spawnSync("ffprobe", ["-v", "quiet", "-show_entries", "format=duration", "-of", "csv=p=0", `${PUBLIC_DIR}/${audio}`], { encoding: "utf-8" });
        const totalSecs = parseFloat(probeR.stdout.trim());
        const bounds = detectSpeechBounds(`${PUBLIC_DIR}/${audio}`, totalSecs);
        audioConfig[key] = { ...audioConfig[key], ...bounds };
        changed = true;
        console.log(`[skip] ${audio}  speechStartFrame → ${bounds.speechStartFrame}, speechEndFrame → ${bounds.speechEndFrame} (재측정)`);
      } else {
        console.log(`[skip] ${audio}`);
      }
    }
    continue;
  }

  console.log(`[gen]  ${audio}`);

  // 1) TTS 생성
  const ttsRes = spawnSync(
    "edge-tts",
    ["--voice", VOICE, "--rate", RATE, "--text", ttsText, "--write-media", `${PUBLIC_DIR}/${audio}`],
    { stdio: "inherit" }
  );
  if (ttsRes.status !== 0) { console.error(`❌  Failed: ${audio}`); process.exit(1); }

  // 2) durationInFrames
  const probeRes = spawnSync("ffprobe", ["-v", "quiet", "-show_entries", "format=duration", "-of", "csv=p=0", `${PUBLIC_DIR}/${audio}`], { encoding: "utf-8" });
  const totalSecs = parseFloat(probeRes.stdout.trim());
  console.log(`       실측 ${totalSecs.toFixed(2)}s`);
  audioConfig[key] = { durationInFrames: Math.ceil(totalSecs * FPS) + SCENE_TAIL_FRAMES, narrationSplits: [], sentenceEndFrames: [], speechStartFrame: 0, speechEndFrame: 0, wordStartFrames: [] };

  // 3) speechStartFrame / speechEndFrame
  const bounds = detectSpeechBounds(`${PUBLIC_DIR}/${audio}`, totalSecs);
  audioConfig[key].speechStartFrame = bounds.speechStartFrame;
  audioConfig[key].speechEndFrame   = bounds.speechEndFrame;
  console.log(`       speechStartFrame → ${bounds.speechStartFrame} (${(bounds.speechStartFrame / FPS).toFixed(2)}s)`);
  console.log(`       speechEndFrame   → ${bounds.speechEndFrame} (${(bounds.speechEndFrame / FPS).toFixed(2)}s)`);

  // 4) narrationSplits / sentenceEndFrames
  const { splits, sentenceEndFrames } = detectSplits(`${PUBLIC_DIR}/${audio}`, narration.length);
  if (splits.length > 0) {
    audioConfig[key].narrationSplits   = splits;
    audioConfig[key].sentenceEndFrames = sentenceEndFrames;
    console.log(`       narrationSplits    → [${splits.join(", ")}] ✅`);
    console.log(`       sentenceEndFrames  → [${sentenceEndFrames.join(", ")}]`);
  }

  // 5) Whisper 단어 타임스탬프 → wordStartFrames (문장별 분류 + PRONUNCIATION 정렬 기반)
  //    전략:
  //      A) Whisper 단어들을 문장별로 분류: 연속 단어 간 gap > SENTENCE_GAP_FRAMES이면 새 문장
  //      B) 분류 수 = narration.length이면 문장별 TTS 비율 매핑 (가장 정확)
  //      C) 불일치면 전역 비율 fallback (구 방식)
  //    이유: Whisper가 한 TTS 단어를 여러 단어로 쪼개면(예: "출력해보겠습니다." → 2개)
  //          전역 비율이 이후 단어를 모두 1개씩 앞 Whisper 단어로 밀어버림.
  //          문장별 분류는 이 drift를 문장 단위로 격리해 누적을 방지.
  audioConfig[key].wordStartFrames = narration.map(() => []);  // 기본: 빈 배열

  const venvPython = path.join(process.cwd(), ".venv", "bin", "python");
  const whisperScript = path.join(process.cwd(), "scripts", "whisper_words.py");
  const whisperRes = spawnSync(
    venvPython,
    [whisperScript, `${PUBLIC_DIR}/${audio}`],
    { encoding: "utf-8" }
  );

  if (whisperRes.status === 0 && whisperRes.stdout.trim()) {
    type WhisperWord = { start: number; end: number; word: string };
    let allWhisperWords: WhisperWord[] = [];
    try { allWhisperWords = JSON.parse(whisperRes.stdout.trim()) as WhisperWord[]; } catch { /* ignore */ }

    if (allWhisperWords.length > 0) {
      // ── A) Whisper 단어를 문장별로 분류 (gap 기반) ──────────────
      const SENTENCE_GAP_FRAMES = 20;  // 0.67s 이상 gap → 새 문장 경계
      const whisperSentences: WhisperWord[][] = [];
      let curSentence: WhisperWord[] = [allWhisperWords[0]];
      for (let i = 1; i < allWhisperWords.length; i++) {
        const gap = (allWhisperWords[i].start - allWhisperWords[i - 1].start) * FPS;
        if (gap > SENTENCE_GAP_FRAMES) {
          whisperSentences.push(curSentence);
          curSentence = [];
        }
        curSentence.push(allWhisperWords[i]);
      }
      whisperSentences.push(curSentence);

      const useSentenceLocal = whisperSentences.length === narration.length;
      if (!useSentenceLocal) {
        console.log(`       whisper sentences → ${whisperSentences.length} (narration: ${narration.length}) — 전역 비율 fallback`);
      }

      // ── B/C) 문장별 또는 전역 비율로 프레임 계산 ──────────────
      const { globalTtsCount, displayWords: dwInfos } = buildGlobalAlignment(narration, PRONUNCIATION);
      const T = globalTtsCount;

      const result: number[][] = narration.map(() => []);
      for (let si = 0; si < narration.length; si++) {
        const sentenceDws = dwInfos.filter((dw) => dw.sentenceIdx === si);

        // 문장별 매핑 준비 (useSentenceLocal=true 시 사전 계산)
        let ws: WhisperWord[] = allWhisperWords;
        let sentenceTtsCount = T;
        let localDwInfos: DisplayWordInfo[] = dwInfos;
        if (useSentenceLocal) {
          ws = whisperSentences[si];
          const aligned = buildGlobalAlignment([narration[si]], PRONUNCIATION);
          sentenceTtsCount = aligned.globalTtsCount;
          localDwInfos = aligned.displayWords;  // sentenceIdx=0, displayIdx 동일
        }

        // Pass 1: 비-zero TTS 단어의 프레임 계산
        const rawFrames: (number | null)[] = sentenceDws.map((dw) => {
          if (dw.ttsCount === 0) return null;
          const localDw = useSentenceLocal
            ? localDwInfos.find((d) => d.displayIdx === dw.displayIdx)
            : dw;
          if (!localDw) return null;
          const localT = useSentenceLocal ? sentenceTtsCount : T;
          const ratio = localT <= 1 ? 0 : localDw.firstTtsIdx / (localT - 1);
          const wIdx = Math.min(ws.length - 1, Math.round(ratio * (ws.length - 1)));
          return Math.round(ws[wIdx].start * FPS);
        });

        // Pass 2: zero-TTS 단어 채우기
        const firstNonNull = rawFrames.find((f) => f !== null) ?? audioConfig[key].speechStartFrame;
        let lastNonNull = firstNonNull;
        let seenNonNull = false;

        for (let i = 0; i < sentenceDws.length; i++) {
          const dw = sentenceDws[i];
          if (rawFrames[i] !== null) {
            lastNonNull = rawFrames[i]!;
            seenNonNull = true;
            result[si][dw.displayIdx] = rawFrames[i]!;
          } else {
            result[si][dw.displayIdx] = seenNonNull ? lastNonNull : firstNonNull;
          }
        }
      }

      audioConfig[key].wordStartFrames = result;
      console.log(`       wordStartFrames   → ${result.map((s) => `[${s.join(",")}]`).join(" | ")}`);
    }
  } else {
    console.log(`       wordStartFrames   → Whisper 실패 (빈 배열)`);
    if (whisperRes.stderr) console.error(whisperRes.stderr.slice(0, 300));
  }

  hashes[key] = newHash;
  changed = true;
}

if (changed) {
  writeAudioConfig(audioConfig);
  writeFileSync(HASH_FILE, JSON.stringify(hashes, null, 2));
  console.log("\n✅  Done. Hashes updated.");
} else {
  console.log("\n✅  All audio up to date.");
}
