/**
 * scripts/sync.ts
 *
 * 사용법: pnpm sync <series>/<id>
 *   예)  pnpm sync 001-Java-Basic/001
 *
 * 자동 처리:
 *  1. narration 텍스트 해시로 변경된 씬만 감지
 *  2. edge-tts 로 mp3 재생성
 *  3. ffprobe 로 실측 duration → durationInFrames 계산
 *  4. ffmpeg silencedetect(-40dB) 로 발화 시작/종료 프레임 감지 → speechStartFrame / speechEndFrame
 *  5. ffmpeg silencedetect(-25dB) 로 문장 분기 프레임 감지 → narrationSplits / sentenceEndFrames
 *  6. 결과를 <id>-audio.ts 파일로 자동 저장
 */

import { buildSync } from "esbuild";
import { createHash } from "crypto";
import { readFileSync, writeFileSync, existsSync, readdirSync } from "fs";
import { spawnSync } from "child_process";
import path from "path";

const FPS = 30;
const SCENE_TAIL_FRAMES = 15;
const PUBLIC_DIR = "public";
const SRC_DIR = "src/compositions";

// ── CLI 인수 ───────────────────────────────────────────────────
const arg = process.argv[2];
if (!arg) {
  console.error("Usage: pnpm sync <series>/<id>   e.g.  pnpm sync 001-Java-Basic/001");
  process.exit(1);
}
const argParts   = arg.split("/");
const episodeId  = argParts[argParts.length - 1];
const SERIES_DIR = path.join(SRC_DIR, ...argParts.slice(0, -1));
const compositionId = episodeId;

const matchEntry = readdirSync(SERIES_DIR).find(
  (f) => f.startsWith(episodeId + "-") && f.endsWith(".tsx")
);
if (!matchEntry) {
  console.error(`❌  ${SERIES_DIR}/${episodeId}-*.tsx 파일을 찾을 수 없습니다.`);
  process.exit(1);
}
const COMPOSITION_FILE = path.join(SERIES_DIR, matchEntry);
const COMPOSITION_DIR  = SERIES_DIR;
const HASH_FILE = `.${arg.replace(/\//g, "-")}-audio-hashes.json`;
console.log(`📄  ${COMPOSITION_FILE}\n`);

// ── AUDIO_CONFIG 스텁 생성 ─────────────────────────────────────
const _audioConfigBootstrap = path.join(COMPOSITION_DIR, compositionId + "-audio.ts");
if (!existsSync(_audioConfigBootstrap)) {
  writeFileSync(
    _audioConfigBootstrap,
    `// AUTO-GENERATED by \`pnpm sync ${compositionId}\` — do not edit manually\n\nconst _stub = { durationInFrames: 30, narrationSplits: [] as number[] };\nexport const AUDIO_CONFIG: Record<string, { durationInFrames: number; narrationSplits: number[] }> = new Proxy({}, { get: () => _stub });\n`,
    "utf-8"
  );
  if (existsSync(HASH_FILE)) writeFileSync(HASH_FILE, "{}", "utf-8");
}

// ── VIDEO_CONFIG 로드 ──────────────────────────────────────────
type SceneEntry = { narration?: string[]; audio: string; };

function loadConfig(): {
  VOICE: string; RATE: string;
  PRONUNCIATION: Record<string, string>;
  VIDEO_CONFIG: Record<string, SceneEntry>;
} {
  const result = buildSync({
    entryPoints: [COMPOSITION_FILE], bundle: true,
    platform: "node", format: "cjs", write: false,
    packages: "external", logLevel: "silent",
  });
  const code = result.outputFiles[0].text;
  const mod = { exports: {} as Record<string, unknown> };
  const stub = new Proxy({}, {
    get(_: object, prop: string | symbol) {
      if (prop === "then") return undefined;
      return (...args: unknown[]) => { void args; return stub; };
    },
  });
  const realRequire = require;
  const mockRequire = (id: string): unknown => {
    if (id === "react" || id === "remotion" || id.startsWith("@remotion/")) return stub;
    return realRequire(id);
  };
  new Function("module", "exports", "require", code)(mod, mod.exports, mockRequire);
  return mod.exports as ReturnType<typeof loadConfig>;
}

const { VOICE, RATE, PRONUNCIATION, VIDEO_CONFIG } = loadConfig();

// ── 유틸 ──────────────────────────────────────────────────────
type Hashes = Record<string, string>;

function hash(text: string): string {
  return createHash("sha256").update(text).digest("hex").slice(0, 16);
}
function loadHashes(): Hashes {
  if (!existsSync(HASH_FILE)) return {};
  return JSON.parse(readFileSync(HASH_FILE, "utf-8")) as Hashes;
}
function applyPronunciation(text: string): string {
  let r = text;
  for (const [k, v] of Object.entries(PRONUNCIATION)) r = r.replaceAll(k, v);
  return r;
}

// ── 발화 시작/종료 프레임 감지 (speechStartFrame / speechEndFrame) ─
function detectSpeechBounds(audioFile: string, totalSecs: number): { speechStartFrame: number; speechEndFrame: number } {
  const ffRes = spawnSync(
    "ffmpeg",
    ["-i", audioFile, "-af", "silencedetect=n=-40dB:d=0.03", "-f", "null", "-"],
    { encoding: "utf-8" }
  );
  const output = (ffRes.stderr ?? "") + (ffRes.stdout ?? "");
  const silences: { start: number; end: number | null }[] = [];
  let pendingStart: number | null = null;
  for (const line of output.split("\n")) {
    const startM = line.match(/silence_start:\s*([\d.]+)/);
    if (startM) pendingStart = parseFloat(startM[1]);
    const endM = line.match(/silence_end:\s*([\d.]+)/);
    if (endM) {
      silences.push({ start: pendingStart ?? 0, end: parseFloat(endM[1]) });
      pendingStart = null;
    }
  }
  if (pendingStart !== null) silences.push({ start: pendingStart, end: null });

  let speechStartFrame = 0;
  const leading = silences.find((s) => s.start < 0.5 && s.end !== null);
  if (leading) speechStartFrame = Math.round(leading.end! * FPS);

  let speechEndFrame = Math.ceil(totalSecs * FPS);
  const trailing = [...silences].reverse().find((s) => s.end === null || s.end >= totalSecs - 0.1);
  if (trailing) speechEndFrame = Math.round(trailing.start * FPS);

  return { speechStartFrame, speechEndFrame };
}

// ── 문장 분기 프레임 감지 (narrationSplits / sentenceEndFrames) ─
function detectSplits(audioFile: string, sentenceCount: number): { splits: number[]; sentenceEndFrames: number[] } {
  if (sentenceCount <= 1) return { splits: [], sentenceEndFrames: [] };

  const probeRes = spawnSync(
    "ffprobe",
    ["-v", "quiet", "-show_entries", "format=duration", "-of", "csv=p=0", audioFile],
    { encoding: "utf-8" }
  );
  const totalSecs = parseFloat(probeRes.stdout.trim());

  const ffRes = spawnSync(
    "ffmpeg",
    ["-i", audioFile, "-af", "silencedetect=n=-25dB:d=0.2", "-f", "null", "-"],
    { encoding: "utf-8" }
  );
  const output = (ffRes.stderr ?? "") + (ffRes.stdout ?? "");

  const entries: { start: number; end: number; duration: number }[] = [];
  let pendingStart: number | null = null;
  for (const line of output.split("\n")) {
    const startM = line.match(/silence_start:\s*([\d.]+)/);
    if (startM) pendingStart = parseFloat(startM[1]);
    const m = line.match(/silence_end:\s*([\d.]+)\s*\|\s*silence_duration:\s*([\d.]+)/);
    if (m && pendingStart !== null) {
      entries.push({ start: pendingStart, end: parseFloat(m[1]), duration: parseFloat(m[2]) });
      pendingStart = null;
    }
  }

  const breaks = entries
    .filter((e) => e.end > 0.4 && e.end < totalSecs - 0.3 && e.duration > 0.25)
    .slice(0, sentenceCount - 1);

  return {
    splits:            breaks.map((b) => Math.round(b.end   * FPS)),
    sentenceEndFrames: breaks.map((b) => Math.round(b.start * FPS)),
  };
}

// ── AUDIO_CONFIG 파일 쓰기 ────────────────────────────────────
type SceneAudioData = {
  durationInFrames: number;
  narrationSplits: number[];
  sentenceEndFrames: number[];
  speechStartFrame: number;
  speechEndFrame: number;
  wordStartFrames: number[][];  // display 단어별 시작 프레임 (문장별, 길이 = displayWords.length)
};

function writeAudioConfig(config: Record<string, SceneAudioData>): void {
  const audioConfigFile = path.join(COMPOSITION_DIR, compositionId + "-audio.ts");
  const lines = Object.entries(config)
    .map(([k, v]) => {
      const wfStr = (v.wordStartFrames ?? []).map((s) => `[${s.join(",")}]`).join(",");
      return `  ${k.padEnd(16)}: { durationInFrames: ${v.durationInFrames}, narrationSplits: [${v.narrationSplits.join(", ")}], sentenceEndFrames: [${v.sentenceEndFrames.join(", ")}], speechStartFrame: ${v.speechStartFrame}, speechEndFrame: ${v.speechEndFrame}, wordStartFrames: [${wfStr}] },`;
    })
    .join("\n");
  const content = `// AUTO-GENERATED by \`pnpm sync ${compositionId}\` — do not edit manually\n\nexport const AUDIO_CONFIG = {\n${lines}\n} as const;\n`;
  writeFileSync(audioConfigFile, content, "utf-8");
  console.log(`\n📝  ${audioConfigFile} 업데이트 완료`);
}

// ── 메인 루프 ─────────────────────────────────────────────────
const hashes = loadHashes();
let changed = false;

const audioConfigFile = path.join(COMPOSITION_DIR, compositionId + "-audio.ts");
let existingAudioConfig: Record<string, SceneAudioData> = {};
if (existsSync(audioConfigFile)) {
  try {
    const raw = readFileSync(audioConfigFile, "utf-8");
    for (const line of raw.split("\n")) {
      const m = line.match(/^\s+(\w+)\s*:\s*\{ durationInFrames: (\d+), narrationSplits: \[([^\]]*)\], sentenceEndFrames: \[([^\]]*)\], speechStartFrame: (\d+), speechEndFrame: (\d+)/);
      if (m) {
        const splits = m[3].trim() ? m[3].split(",").map(s => parseInt(s.trim())) : [];
        const ends   = m[4].trim() ? m[4].split(",").map(s => parseInt(s.trim())) : [];
        existingAudioConfig[m[1]] = { durationInFrames: parseInt(m[2]), narrationSplits: splits, sentenceEndFrames: ends, speechStartFrame: parseInt(m[5]), speechEndFrame: parseInt(m[6]), wordStartFrames: [] };
        // wordStartFrames 중첩 배열 파싱
        const wfIdx = line.indexOf("wordStartFrames: ");
        if (wfIdx !== -1) {
          const start = line.indexOf("[", wfIdx);
          if (start !== -1) {
            let depth = 0, end = -1;
            for (let i = start; i < line.length; i++) {
              if (line[i] === "[") depth++;
              else if (line[i] === "]") { depth--; if (depth === 0) { end = i; break; } }
            }
            if (end !== -1) {
              try { existingAudioConfig[m[1]].wordStartFrames = JSON.parse(line.slice(start, end + 1)) as number[][]; } catch { /* ignore */ }
            }
          }
        }
        continue;
      }
      // 구버전 호환
      const m2 = line.match(/^\s+(\w+)\s*:\s*\{ durationInFrames: (\d+), narrationSplits: \[([^\]]*)\]/);
      if (m2) {
        const splits = m2[3].trim() ? m2[3].split(",").map(s => parseInt(s.trim())) : [];
        existingAudioConfig[m2[1]] = { durationInFrames: parseInt(m2[2]), narrationSplits: splits, sentenceEndFrames: [], speechStartFrame: 0, speechEndFrame: 0, wordStartFrames: [] };
      }
    }
  } catch { /* ignore */ }
}

const audioConfig: Record<string, SceneAudioData> = {};

for (const [key, scene] of Object.entries(VIDEO_CONFIG)) {
  const narration = scene.narration;
  if (!narration) continue;

  const ttsText = applyPronunciation(narration.join(" "));
  const audio = scene.audio;
  const newHash = hash(VOICE + RATE + ttsText);

  if (hashes[key] === newHash) {
    if (existingAudioConfig[key]) {
      audioConfig[key] = existingAudioConfig[key];
      if (audioConfig[key].speechStartFrame === 0 || audioConfig[key].speechEndFrame === 0) {
        const probeR = spawnSync("ffprobe", ["-v", "quiet", "-show_entries", "format=duration", "-of", "csv=p=0", `${PUBLIC_DIR}/${audio}`], { encoding: "utf-8" });
        const totalSecs = parseFloat(probeR.stdout.trim());
        const bounds = detectSpeechBounds(`${PUBLIC_DIR}/${audio}`, totalSecs);
        audioConfig[key] = { ...audioConfig[key], ...bounds };
        changed = true;
        console.log(`[skip] ${audio}  speechStartFrame → ${bounds.speechStartFrame}, speechEndFrame → ${bounds.speechEndFrame} (재측정)`);
      } else {
        console.log(`[skip] ${audio}`);
      }
    }
    continue;
  }

  console.log(`[gen]  ${audio}`);

  // 1) TTS 생성
  const ttsRes = spawnSync(
    "edge-tts",
    ["--voice", VOICE, "--rate", RATE, "--text", ttsText, "--write-media", `${PUBLIC_DIR}/${audio}`],
    { stdio: "inherit" }
  );
  if (ttsRes.status !== 0) { console.error(`❌  Failed: ${audio}`); process.exit(1); }

  // 2) durationInFrames
  const probeRes = spawnSync("ffprobe", ["-v", "quiet", "-show_entries", "format=duration", "-of", "csv=p=0", `${PUBLIC_DIR}/${audio}`], { encoding: "utf-8" });
  const totalSecs = parseFloat(probeRes.stdout.trim());
  console.log(`       실측 ${totalSecs.toFixed(2)}s`);
  audioConfig[key] = { durationInFrames: Math.ceil(totalSecs * FPS) + SCENE_TAIL_FRAMES, narrationSplits: [], sentenceEndFrames: [], speechStartFrame: 0, speechEndFrame: 0, wordStartFrames: [] };

  // 3) speechStartFrame / speechEndFrame
  const bounds = detectSpeechBounds(`${PUBLIC_DIR}/${audio}`, totalSecs);
  audioConfig[key].speechStartFrame = bounds.speechStartFrame;
  audioConfig[key].speechEndFrame   = bounds.speechEndFrame;
  console.log(`       speechStartFrame → ${bounds.speechStartFrame} (${(bounds.speechStartFrame / FPS).toFixed(2)}s)`);
  console.log(`       speechEndFrame   → ${bounds.speechEndFrame} (${(bounds.speechEndFrame / FPS).toFixed(2)}s)`);

  // 4) narrationSplits / sentenceEndFrames
  const { splits, sentenceEndFrames } = detectSplits(`${PUBLIC_DIR}/${audio}`, narration.length);
  if (splits.length > 0) {
    audioConfig[key].narrationSplits   = splits;
    audioConfig[key].sentenceEndFrames = sentenceEndFrames;
    console.log(`       narrationSplits    → [${splits.join(", ")}] ✅`);
    console.log(`       sentenceEndFrames  → [${sentenceEndFrames.join(", ")}]`);
  }

  // 5) Whisper 단어 타임스탬프 → wordStartFrames (display 단어 개수 길이)
  audioConfig[key].wordStartFrames = narration.map(() => []);  // 기본: 빈 배열

  const venvPython = path.join(process.cwd(), ".venv", "bin", "python");
  const whisperScript = path.join(process.cwd(), "scripts", "whisper_words.py");
  const whisperRes = spawnSync(
    venvPython,
    [whisperScript, `${PUBLIC_DIR}/${audio}`],
    { encoding: "utf-8" }
  );

  if (whisperRes.status === 0 && whisperRes.stdout.trim()) {
    type WhisperWord = { start: number; end: number; word: string };
    let allWhisperWords: WhisperWord[] = [];
    try { allWhisperWords = JSON.parse(whisperRes.stdout.trim()) as WhisperWord[]; } catch { /* ignore */ }

    if (allWhisperWords.length > 0) {
      // 문장별 Whisper 단어 분류 (narrationSplits 기준)
      const sentenceStarts = [audioConfig[key].speechStartFrame, ...audioConfig[key].narrationSplits];
      const sentenceWhisperWords: WhisperWord[][] = narration.map(() => []);
      for (const w of allWhisperWords) {
        const wFrame = Math.round(w.start * FPS);
        for (let i = sentenceStarts.length - 1; i >= 0; i--) {
          if (wFrame >= sentenceStarts[i] - 3) {
            sentenceWhisperWords[i].push(w);
            break;
          }
        }
      }

      // 각 문장: display 단어 개수 길이 배열로 위치 보간
      audioConfig[key].wordStartFrames = narration.map((sentence, si) => {
        const displayWords = sentence.split(" ");
        const whisperSentenceWords = sentenceWhisperWords[si];
        if (whisperSentenceWords.length === 0) return displayWords.map(() => sentenceStarts[si]);
        return displayWords.map((_, displayIdx) => {
          const ratio = displayWords.length === 1 ? 0 : displayIdx / (displayWords.length - 1);
          const whisperIdx = Math.round(ratio * (whisperSentenceWords.length - 1));
          return Math.round(whisperSentenceWords[whisperIdx].start * FPS);
        });
      });

      console.log(`       wordStartFrames   → ${audioConfig[key].wordStartFrames.map((s) => `[${s.join(",")}]`).join(" | ")}`);
    }
  } else {
    console.log(`       wordStartFrames   → Whisper 실패 (빈 배열)`);
    if (whisperRes.stderr) console.error(whisperRes.stderr.slice(0, 300));
  }

  hashes[key] = newHash;
  changed = true;
}

if (changed) {
  writeAudioConfig(audioConfig);
  writeFileSync(HASH_FILE, JSON.stringify(hashes, null, 2));
  console.log("\n✅  Done. Hashes updated.");
} else {
  console.log("\n✅  All audio up to date.");
}
